### ISSUE TITLE
Using dockerComposeUp to start the stack, fails to find Redis at startup

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#1394]

**Comment by gfoo** [comment]
Is this related to this error:
```
webapi_1   | 2019-08-16 08:14:10 | WARN  | LiveCore$$anon$1 | Redis-Server not running. Please start the Redis-Server.
```
I didn't find a workaround, tried to restart `redis` and/or `webapi` containers but I still stuck with this error.

**Comment by gfoo** [comment]
By adding the `redis` container into the `knora-net`, it works:
```
  redis:
    image: redis:5
    ports:
      - "6379:6379"
    networks:
      - knora-net
```
But maybe you have a good reason to not add this net config.
